/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AddDestinationDialog: typeof import('./views/master/components/AddDestinationDialog.vue')['default']
    AddIdentityDialog: typeof import('./views/master/components/AddIdentityDialog.vue')['default']
    AddVehicleDialog: typeof import('./views/master/components/AddVehicleDialog.vue')['default']
    AddVendorDialog: typeof import('./views/master/components/AddVendorDialog.vue')['default']
    AddVisitorPurposeDialog: typeof import('./views/master/components/AddVisitorPurposeDialog.vue')['default']
    ChildCard: typeof import('./components/ChildCard.vue')['default']
    FooterPanel: typeof import('./layouts/internal/footer/FooterPanel.vue')['default']
    Internal: typeof import('./layouts/internal.vue')['default']
    LogoMain: typeof import('./layouts/internal/logo/LogoMain.vue')['default']
    NavCollapse: typeof import('./layouts/internal/vertical-sidebar/NavCollapse/NavCollapse.vue')['default']
    NavItem: typeof import('./layouts/internal/vertical-sidebar/NavItem/NavItem.vue')['default']
    ParentCard: typeof import('./components/ParentCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    VehicleChart: typeof import('./components/charts/VehicleChart.vue')['default']
    VendorChart: typeof import('./components/charts/VendorChart.vue')['default']
    VerticalHeader: typeof import('./layouts/internal/vertical-header/VerticalHeader.vue')['default']
    VerticalSidebar: typeof import('./layouts/internal/vertical-sidebar/VerticalSidebar.vue')['default']
    VisitorChart: typeof import('./components/charts/VisitorChart.vue')['default']
  }
}
